// Copyright (c) 2026 Neomantra Corp

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
	"strings"
	"text/tabwriter"
	"time"

	flag "github.com/spf13/pflag"

	"github.com/neomantra/CivicSodaQuack/internal/duckdb"
	"github.com/neomantra/CivicSodaQuack/internal/socrata"
)

func runCatalog(args []string) error {
	fs := flag.NewFlagSet("catalog", flag.ContinueOnError)
	var (
		portal   string
		dbPath   string
		appToken string
		refresh  bool
		asJSON   bool
		output   string
		force    bool
	)
	var ids, names, cats, tags []string

	fs.StringVar(&portal, "portal", "", "Socrata portal host")
	fs.StringVar(&dbPath, "db", "", "DuckDB file (default: <portal>.duckdb)")
	fs.StringVarP(&appToken, "token", "t", os.Getenv("SOCRATA_APP_TOKEN"), "Socrata app token")
	fs.BoolVar(&refresh, "refresh", false, "Force refetch of catalog")
	fs.BoolVar(&asJSON, "json", false, "Emit JSON instead of a table")
	fs.StringVar(&output, "output", "", "Write a starter YAML to this path instead of printing")
	fs.BoolVar(&force, "force", false, "Overwrite --output file if it exists")
	fs.StringArrayVar(&ids, "id", nil, "Literal 4x4 id filter (repeatable)")
	fs.StringArrayVar(&names, "name", nil, "Glob match on name (repeatable)")
	fs.StringArrayVar(&cats, "category", nil, "Glob match on category (repeatable)")
	fs.StringArrayVar(&tags, "tag", nil, "Glob match on tag (repeatable)")

	if err := fs.Parse(args); err != nil {
		return err
	}
	if portal == "" {
		return fmt.Errorf("--portal is required")
	}
	if dbPath == "" {
		dbPath = portal + ".duckdb"
	}

	w, err := duckdb.Open(dbPath)
	if err != nil {
		return err
	}
	defer w.Close()

	client := &socrata.Client{AppToken: appToken}

	catalog, err := w.ReadCatalog()
	if err != nil {
		return fmt.Errorf("read cached catalog: %w", err)
	}
	if refresh || len(catalog) == 0 {
		fmt.Fprintf(os.Stderr, "[csq] fetching catalog from %s\n", portal)
		catalog, err = client.FetchCatalog(portal)
		if err != nil {
			return fmt.Errorf("fetch catalog: %w", err)
		}
		if err := w.UpsertCatalog(catalog, time.Now().UTC()); err != nil {
			return fmt.Errorf("cache catalog: %w", err)
		}
	}

	filtered := filterCatalog(catalog, ids, names, cats, tags)

	if output != "" {
		return writeStarterYAML(output, portal, filtered, force)
	}
	if asJSON {
		return json.NewEncoder(os.Stdout).Encode(filtered)
	}
	return printCatalogTable(os.Stdout, filtered)
}

func filterCatalog(catalog []socrata.CatalogEntry, ids, names, cats, tags []string) []socrata.CatalogEntry {
	out := make([]socrata.CatalogEntry, 0, len(catalog))
next:
	for _, e := range catalog {
		if len(ids) > 0 {
			matched := false
			for _, id := range ids {
				if id == e.ID {
					matched = true
					break
				}
			}
			if !matched {
				continue next
			}
		}
		if !anyGlob(names, e.Name) {
			continue next
		}
		if !anyGlob(cats, e.Category) {
			continue next
		}
		if len(tags) > 0 {
			matched := false
			for _, tag := range tags {
				for _, t := range e.Tags {
					if ok, _ := path.Match(tag, t); ok {
						matched = true
						break
					}
				}
				if matched {
					break
				}
			}
			if !matched {
				continue next
			}
		}
		out = append(out, e)
	}
	return out
}

// anyGlob returns true if patterns is empty, or if any pattern matches s.
func anyGlob(patterns []string, s string) bool {
	if len(patterns) == 0 {
		return true
	}
	for _, p := range patterns {
		if ok, _ := path.Match(p, s); ok {
			return true
		}
	}
	return false
}

func printCatalogTable(out *os.File, entries []socrata.CatalogEntry) error {
	tw := tabwriter.NewWriter(out, 0, 0, 2, ' ', 0)
	fmt.Fprintln(tw, "ID\tNAME\tCATEGORY\tROWS\tUPDATED")
	for _, e := range entries {
		rc := "-"
		if e.RowCount != nil {
			rc = fmt.Sprintf("%d", *e.RowCount)
		}
		upd := "-"
		if e.UpdatedAt != nil {
			upd = e.UpdatedAt.Format("2006-01-02")
		}
		name := e.Name
		if len(name) > 40 {
			name = name[:37] + "..."
		}
		fmt.Fprintf(tw, "%s\t%s\t%s\t%s\t%s\n", e.ID, name, e.Category, rc, upd)
	}
	return tw.Flush()
}

func writeStarterYAML(path, portal string, entries []socrata.CatalogEntry, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("%s exists; pass --force to overwrite", path)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by csq catalog --output\n")
	fmt.Fprintf(&b, "portal: %s\n", portal)
	fmt.Fprintf(&b, "on_error: continue\n")
	fmt.Fprintf(&b, "concurrency: 4\n\n")
	fmt.Fprintf(&b, "defaults:\n  batch_size: 5000\n  order_by: \":id\"\n\n")
	fmt.Fprintf(&b, "include:\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "  # - id: %s   # %s\n", e.ID, e.Name)
	}
	fmt.Fprintf(&b, "\nexclude: []\n\noverrides: {}\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
